#!/bin/bash
set -e

curl https://raw.githubusercontent.com/oracle/fastr/master/mx.fastr/suite.py -O
GNUR_VERSION=$(cat suite.py | grep "cran" | grep -o '[0-9]\.[0-9]\.[0-9]')

echo "Add version tag"
docker tag $IMAGE_NAME $DOCKER_REPO:devel
docker push $DOCKER_REPO:devel

echo "Add R version tag"
docker tag $IMAGE_NAME $DOCKER_REPO:R-$GNUR_VERSION
docker push $DOCKER_REPO:R-$GNUR_VERSION
